---
name: Build and Publish Crossfire Metaserver Docker Image

"on":
  push:
    branches:
      - vscode-devcontainer
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD_METASERVER }}

      - name: Build and Push www service
        uses: docker/build-push-action@v5
        with:
          context: ./docker/www
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}  # Don't push on PRs
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/crossfire-metaserver-www:latest

      - name: Build and Push certbot service
        uses: docker/build-push-action@v5
        with:
          context: ./docker/certbot
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/crossfire-metaserver-certbot:latest
