---
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [www]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD_METASERVER }}

      - name: Build and Push ${{ matrix.service }} service
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --file docker/${{ matrix.service }}/Dockerfile \
            --tag ${{ secrets.DOCKER_USERNAME }}/crossfire-metaserver-${{ matrix.service }}:latest \
            --push=${{ github.event_name != 'pull_request' }} \
            .
      - name: Build Docker image
        run: |
          docker compose -f docker-compose.yml build

      - name: Tag and Push Docker images
        run: |
          for SERVICE in crossfire-metaserver_www; do
            IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/$SERVICE
            IMAGE_TAG=latest
            docker tag $SERVICE $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:$IMAGE_TAG
          done
